### ISSUE TITLE
Create Collections 

### ISSUE THREAD

**Issue by margaretlhe** [JakeAdler/Rove#18]
**Is your feature request related to a problem? Please describe.**
-We need to store and save the data of our vendors and customers.

**Describe the solution you'd like**
Create collections for:
-vendors (id, name, food service, open/closed boolean, etc.)
-customers (id, name)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by germanp173** [comment]
The customers and vendors collections have been created in our `RoveBase` database. The schema, however, will be defined in the front-end with the use of stitch.
