### ISSUE TITLE
Create Rover Repo for Microservice

### ISSUE THREAD

**Issue by margaretlhe** [JakeAdler/Rove#21]
**Is your feature request related to a problem? Please describe.**
- We need a microservice to acquire all vendor locations in the customer's nearby vicinity.

**Describe the solution you'd like**
Setup initial file structure (express app).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JakeAdler** [comment]
https://github.com/JakeAdler/Rover
