### ISSUE TITLE
Geospatial

### ISSUE THREAD

**Issue by margaretlhe** [JakeAdler/Rove#8]
**Describe the issue you are trying to solve .**
-We need a microservice to acquire all vendor locations in the customer's nearby vicinity

**Describe the solution you'd like**
-The geospatial service should acquire all vendors near the customer's location and return these vendor locations from MongoDB 

**Describe alternatives you've considered**
-N/A

**Comment by germanp173** [comment]
Potential Tickets for this Epic:
- Research the type of location that iPhone gives you through React Native
- Match type of location with MongoDB property
